### ISSUE TITLE
XML File issue

### ISSUE THREAD

**Issue by discentem** [atom/language-property-list#13]
Still persistent: https://github.com/atom/language-property-list/issues/5

This is annoyance for Mac Administrators especially, who work with these files a lot.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
